#!/usr/bin/env bash

set -o pipefail
shopt -s expand_aliases

export BASHFUL_SETUP_ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "./lib/setup-source.sh";


install_alias
bashful config