#!/usr/bin/env bash
  
  #-----------------------------------------------------------------
  #
  #
  #
  #
  #
  #-----------------------------------------------------------------

  #----------------------
    COLOR_NONE='\e[0m';
    COLOR_GREEN='\e[1;32m';
    COLOR_RED='\e[0;31m';
    COLOR_BLUE='\e[0;34m';
    COLOR_CYAN='\e[1;36m';
    COLOR_GREY='\e[1;90m';
    COLOR_WHITE='\e[0;37m';
    PASS='\xE2\x9C\x93';
    FAIL='\xE2\x9C\x97';
  #----------------------


  #----------------------
    set -o pipefail
    shopt -s expand_aliases
    CURR_DIR="$(pwd)"
  #----------------------


  #----------------------
    #setup file must be sourced
    if [ "$0" = "-bash" ]; then
      
      #export paths and functions to setup BASHFUL
      export BASHFUL_SETUP_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
      source "./inc/setup-exports.sh"

      #only echo instructions in terminal mode
      if [ -t 1 ]; then 
        printf "\n\n${COLOR_GREEN}${PASS} Environment configured for Bashful${COLOR_NONE}\n\n"

        if [ -d $PATH_BASHFUL_ROOT ] && [ -f $PATH_BASHFUL_USER_INSTALL_FILE ]; then 
          printf "> Bashful is currently installed\n"
          printf "${COLOR_BLUE} bashful uninstall ${COLOR_NONE}\n"
        else
          printf "> Bashful is not currently installed\n"
          printf "${COLOR_BLUE} bashful install ${COLOR_NONE}\n"
        fi

        printf "${COLOR_BLUE} bashful clean ${COLOR_NONE}\n"
        printf "${COLOR_BLUE} bashful help ${COLOR_NONE}\n"

      else
        true
      fi

    else
      printf "\n\n${COLOR_RED}${FAIL} BASHFUL SETUP FAILED${COLOR_NONE}\n\n"
      printf "> Bashful needs to setup environment variables before installing. \n"
      printf "Usage: source ./setup\n\n"
      false
    fi
  #----------------------

